# Generated by Django 3.0.1 on 2020-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200721_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='photos/%Y/%m/%d/', width_field=100),
        ),
    ]
