# Generated by Django 3.0.1 on 2020-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200721_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/%Y/%m/%d/'),
        ),
    ]
