# Generated by Django 3.0.1 on 2020-07-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200721_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_about',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='Закупочная цена'),
            preserve_default=False,
        ),
    ]
