# Generated by Django 3.0.1 on 2020-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(default=0, max_length=15, verbose_name='Размер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(max_length=10, verbose_name='Закупочная цена'),
        ),
    ]
