# Generated by Django 3.0.1 on 2020-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200721_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=0, verbose_name='Номер товара'),
            preserve_default=False,
        ),
    ]
