# Generated by Django 3.0.1 on 2020-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200721_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default='uuid.uuid4', editable=False, primary_key=True, serialize=False),
        ),
    ]
