# Generated by Django 3.0.1 on 2020-07-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200721_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=9999999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
