# Generated by Django 3.0.1 on 2020-07-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200721_1653'),
        ('main', '0004_order_product_task'),
    ]

    operations = [
    ]
