# Generated by Django 3.0.1 on 2020-07-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20200721_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
