# Generated by Django 3.0.1 on 2020-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200721_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=99999, max_length=5, verbose_name='Номер товара'),
            preserve_default=False,
        ),
    ]
