# Generated by Django 3.0.1 on 2020-07-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_product_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='order_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='contain',
            new_name='order_contain',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='order_name',
        ),
    ]
