# Generated by Django 3.0.1 on 2020-07-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200723_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=10, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
