# Generated by Django 3.0.1 on 2020-08-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default=0, max_length=100, verbose_name='Статус заказа'),
            preserve_default=False,
        ),
    ]
