# Generated by Django 3.0.1 on 2020-08-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200804_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_count',
            field=models.CharField(default=0, max_length=3, verbose_name='Доступность'),
        ),
    ]
