# Generated by Django 3.0.1 on 2020-08-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200808_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('sec', 'Среднее'), ('high', 'Высшее'), ('low', 'Низкое')], default='Новый', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
