# Generated by Django 3.0.1 on 2020-08-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200808_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Среднее', 'Среднее'), ('Высшее', 'Высшее'), ('Низкое', 'Низкое')], default='Новый', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
