# Generated by Django 3.0.1 on 2020-08-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200809_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
