# Generated by Django 3.0.1 on 2020-08-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200815_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Новый', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
