# Generated by Django 3.0.1 on 2020-08-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200816_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=999, verbose_name=models.CharField(max_length=5, verbose_name='Номер товара')),
            preserve_default=False,
        ),
    ]
