# Generated by Django 3.0.1 on 2020-08-30 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_tag',
            field=models.CharField(default='null', max_length=50, verbose_name='Тэг'),
        ),
        migrations.AddField(
            model_name='budget',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
