# Generated by Django 3.0.1 on 2020-09-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_order_need_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_need_buy',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
